config/routes.rb
Rails.application.routes.draw do
  resources :locations do
    resources :events
  end

  root 'locations#index'

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :location

end

app/models/location.rb
class Location < ActiveRecord::Base

  has_many :events

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
    @location = Location.find(params[:location_id])
  end

  def create
    @event = Event.new(event_params)
    @event.location_id = params[:location_id]
    @location = Location.find(params[:location_id])
      if @event.save
        redirect_to location_path(@location)
      else
        render :new
      end
  end

  def edit
    @event = Event.find(params[:id])
    @location = Location.find(params[:location_id])
  end

  def update
    @location = Location.find(params[:location_id])
    @event = Event.find(params[:id])
      if @event.update(event_params)
        redirect_to location_path(@location)
      end
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @location = Location.find(params[:location_id])
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to location_path(@location)
  end

  private

  def event_params
    params.require(:event).permit(:description, :date, :requires_id, :location_id)
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
      if @location.save
        redirect_to locations_path
      else
        render :new
      end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
      if @location.update(location_params)
        redirect_to location_path
      end
  end

  def show
    @location = Location.find(params[:id])

  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to locations_path
  end

  private

  def location_params
    params.require(:location).permit(:name, :address, :zipcode)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_form.html.erb
<%= form_for [@location, @event] do |f| %>

<form class="form-horizontal">
  <div class="form-group">
      <%= f.label :description, class: "control-label col-md-2" %>
    <div class="form-controls col-md-4">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>
<br>
<br>
  <div class="form-group">
      <%= f.label :date, class: "control-label col-md-2" %>
    <div class="form-controls col-md-4">
      <%= f.date_select :date, class: "form-control" %>
    </div>
  </div>
<br>
<br>
  <div class="form-group">
      <%= f.label :requires_id, "Requires ID", class: "control-label col-md-2" %>
    <div class="form-controls col-md-1">
      <%= f.check_box :requires_id, class: "form-control" %>
    </div>
  </div>

<br>
<br>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-4">
      <%= f.submit class: "btn btn-primary"%>
      <%= link_to "Cancel", locations_path, class: "btn btn-default"%>
    </div>
  </div>
  <% end %>
</form>

app/views/events/edit.html.erb
<%= render 'form' %>
<br>
<%= link_to "Delete Event", location_event_path, class: "btn btn-danger", method: :delete %>

app/views/events/new.html.erb
<div class="page-header"><h3>Create New Event</h3></div>

<%= render 'form' %>

app/views/events/show.html.erb
<div class="page-header"><div class="pull-right"><%= link_to "Edit Event", edit_location_event_path, class: "btn btn-info" %></div>
  <h2><%=@event.description%></h2></div>


<dl class="dl-horizontal">
<dt>Name</dt>
<dd><%= @event.description %></dd>
<dt>Address</dt>
<dd><%= @event.date %></dd>
<dt>Zip Code</dt>
<dd><%= @event.requires_id %></dd>
</dl>

<br>

<%= link_to "Delete Event", location_event_path, class: "btn btn-danger", method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CalebAtwoodWeek5</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location, html:{class: "form-horizontal"}) do |f| %>

<form class="form-horizontal">
  <div class="form-group">
      <%= f.label :name, class: "control-label col-md-2" %>
    <div class="form-controls col-md-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
<br>
<br>
  <div class="form-group">
      <%= f.label :address, class: "control-label col-md-2" %>
    <div class="form-controls col-md-4">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>
<br>
<br>
  <div class="form-group">
      <%= f.label :zipcode, class: "control-label col-md-2" %>
    <div class="form-controls col-md-4">
      <%= f.text_field :zipcode, class: "form-control" %>
    </div>
  </div>

<br>
<br>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-4">
      <%= f.submit class: "btn btn-primary"%>
      <%= link_to "Cancel", locations_path, class: "btn btn-default"%>
    </div>
  </div>
  <% end %>
</form>

app/views/locations/edit.html.erb
<div class="page-header"><h2>Edit Location</h2></div>

<%= render 'form' %>

<br>
<%= link_to "Delete Location", location_path(@location), class: "btn btn-danger", method: :delete %>

app/views/locations/index.html.erb
<div class="page-header"><h3> <%= link_to "Create New Location", new_location_path %> </h3></div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Zip Code</th>
    </tr>
  </thead>
  <tbody>
    <% @locations.each do |l| %>
    <tr>
      <td> <%= link_to l.name, location_path(l) %> </td>
      <td> <%= l.address %> </td>
      <td> <%= l.zipcode %> </td>
      <td class="text-right">
        <%= link_to "Delete", l, class: "btn btn-danger", method: :delete %>
        <%= link_to "Edit", edit_location_path(l), class: "btn btn-info" %>
        <%= link_to "Create Event", new_location_event_path(l), class: "btn btn-default"  %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/locations/new.html.erb
<div class="page-header"><h3>Create New Location</h3></div>

<%= render 'form' %>

app/views/locations/show.html.erb
<div class="page-header"><div class="pull-right"><%= link_to "Edit Location", edit_location_path, class: "btn btn-info" %></div>
  <h2><%=@location.name%></h2></div>

  <ol class="breadcrumb">
    <li><%= link_to "Home", root_url %></li>
    <li class="active"> <%= @location.name %> </li>
  </ol>

<dl class="dl-horizontal">
<dt>Name</dt>
<dd><%= @location.name %></dd>
<dt>Address</dt>
<dd><%= @location.address %></dd>
<dt>Zip Code</dt>
<dd><%= @location.zipcode %></dd>
</dl>

<h3>Events:</h3>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Description</th>
      <th>Date</th>
      <th>Requires ID?</th>
    </tr>
  </thead>
  <tbody>
    <% @location.events.each do |e| %>
    <tr>
      <td> <%= link_to e.description, location_event_path(@location, e) %> </td>
      <td> <%= e.date %> </td>
      <td> <%= e.requires_id %> </td>
      <td class="text-right">
        <%= link_to "Delete", location_event_path(@location, e), class: "btn btn-danger", method: :delete %>
        <%= link_to "Edit", edit_location_event_path(@location, e), class: "btn btn-info" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>